### ISSUE TITLE
CUDA generator expects graph capture to be underway, but the current stream is not capturing

### ISSUE THREAD

**Issue by Sandeep-Narahari** [huggingface/diffusion-fast#12]
When there will be multiple image generation requests its its throwing  "CUDA generator expects graph capture to be underway, but the current stream is not capturing"

![image](https://github.com/huggingface/diffusion-fast/assets/46187761/a92a1b96-7a0e-4fc3-9de3-f08815646dc5)

![image](https://github.com/huggingface/diffusion-fast/assets/46187761/0fcfbfb7-756e-4392-8269-bffdf7d539cf)

**Comment by sayakpaul** [comment]
This is beyond the control of this repository. What is the minimal way to reproduce this?

**Comment by Sandeep-Narahari** [comment]
Build the basic API ,  using torch compile optimization and make 10- 20  of requests , to the api

**Comment by sayakpaul** [comment]
That is definitely quite out of scope for this repository.
