### ISSUE TITLE
torchao compatibility

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusion-fast#14]
torchao package changed structure of internal mewthods several times and while this repo is quoted in several places (including on actual torchao page), its not compatible with any of the recent versions of torchao

**Comment by sayakpaul** [comment]
That is why the `ao` version with which this repo was tested can be recovered here:
https://github.com/huggingface/diffusion-fast/blob/f4fa861422d9819226eb2ceac247c85c3547130d/Dockerfile#L30

I will add a note mentioning the compatibility and provide a reference to https://github.com/sayakpaul/diffusers-torchao which has most up-to-date usage.

**Comment by sayakpaul** [comment]
Done in https://github.com/huggingface/diffusion-fast/commit/95600855237c3acc917f90a9d07bc05d02544df2.
